language: java
addons:
  sonarcloud:
    organization: andreoss
    token:
      secure: nAj6FhXvMZ5Meyx/o6nMA02paoi0dIU/in5e2oC9jIjIMkZEO5rpEEqYLoQNRuDjj50j1+bSj9WgHtjx77fU+1IM924CjJmLWAQlJStxgitLaC1p8dO1loiQrsdWYXUXfYHV75kyPsdS0HGyR+mEhX5UNEN9f09NV2U4aBTVXcQmPdT6KYc5AvPZEtftMXvyWuVAUJYLY/riALp41TFPZl8wrSowQRdXgYf00q718ZYB/yPjVGZ6S5SEq2Fs35g5LHLYeXEhNl1bhWEXVLcjwCfzdZ4rzR/f8CEnxmDZSUvKucf07onsFWmElUZO0Ka7ntfOF5E+7HKtM4wD9lvj8SlLIJ9M+9GoHhNoLczVu3K3sqmGyqeWPa60vpW1lAlufn76keFDvA5gvU0B8rM97/RoqudOUApSjyE4y24+2ipQV0fZgF2BqRCAivVRC11t9FkjtcsEa3he6oxqfuTNGsfGOhC4Ag85tki1mrKhZKjvt4FKOyIlJLXH5M6pin3qu6v5oKTuRAemSaJGwsyAN06QRDWa2WRx8Ce1eqbu7CVxXJtPj08QycKq1U8jqNq7eh5VdnGNO5mfASGfgopc4Jv34MxTmNesW1eld3dJeM9OnILg9ovDdr9S/lvBdCJdTiUSg3Fng3PfahVi9qSlpS6HH/VuifOGHFH6M5K5iRI=
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=andreoss_mancala

env:
  global:
    - CODECOV_TOKEN="121d6f6b-2c68-4953-936c-4bc6df77832b"

after_success:
  - bash <(curl -s https://codecov.io/bash)
